FROM ubuntu:18.04 AS BUILD

RUN apt-get -y update
RUN apt-get install -y gcc python3 python3-pip python3-dev cmake make libsm6 libxext6 libxrender-dev
RUN apt-get install -y git

RUN git clone https://github.com/opencv/opencv.git
WORKDIR /opencv/build
RUN cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=/usr/local ..
RUN make -j4
RUN make install
